//José María Gómez García A2 DSD

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ServicioBasicoDeRegistro.h"
#include "../DNS2/ServicioBasicoDeRegistro2.h"
#include <vector>
#include <string>
#include <iostream>
#include <sstream>

using namespace std;

char subRed = '1';
vector<pair<string, string> > direcciones;

string createIP() {

	string ip;
	int sub = direcciones.size() + 1;
	stringstream ss;
	ss << sub;

	ip.clear();
	ip += subRed;
	ip += '.';
	ip += ss.str();

	return ip;
}

char **
registra_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static char *  result;
	int existe;

	string nombre(arg1);
	string ip("unknown");
	existe = 0;

	for (int i = 0; i < direcciones.size(); i++) { // or

		if (direcciones[i].first == arg1) {
			existe = 1;
			ip = direcciones[i].second;
		}
	}

	if (existe == 0) {

		ip = createIP();
		direcciones.push_back(pair<string,string>(nombre,ip));
	}

	result = strdup(ip.c_str());

	cout << "Registra " << direcciones.size() << " " << result << ": " << nombre << ", " << ip << endl;

	return &result;
}

int *
borra_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static int  result;
	int donde;
	int encontrado;

	result = 0;
	donde = 0;
	encontrado = 0;

	for (int i = 0; i < direcciones.size(); i++) {
		if (direcciones[i].first == arg1) {
			encontrado = 1;
			donde = i;
		}
	}

	if (encontrado == 1) {
		direcciones.erase(direcciones.begin()+donde);
		result = 1;
	}

	cout << "Borra " << arg1 << ": " << result << endl;

	return &result;
}

char **
buscaip_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static char * result;
	char * *resultHost;
	char *host;
	CLIENT *clnt;
	const string str = "No se ha encontrado";
	const string hostip = "localhost";
	int encontrado;

	result = strdup(str.c_str());
	host = strdup(hostip.c_str());
	encontrado = 0;

	for (int i = 0; i < direcciones.size(); i++) {

		if (direcciones[i].first == arg1) {
			strcpy(result, direcciones[i].second.c_str());
			encontrado = 1;
		}

	}

	if (encontrado == 0) {

		clnt = clnt_create (host, SERVICIOBASICODEREGISTRO2, DNS2, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}

		resultHost = buscaip_2(arg1, clnt);
		if (resultHost == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}

		result = *resultHost;
	}

	cout << "Buscaip " << arg1 << ": " << result << endl;

	return &result;
}

// EXÁMEN ////////////////////////////////////////////////////////////

char **
visualizartabladns_1_svc(struct svc_req *rqstp)
{
	static char * result;
	string tabla;
	
	tabla.clear();

	if (direcciones.size() > 0) {

		for (int i = 0; i < direcciones.size(); i++) {
		
			tabla += '\n';
			tabla += direcciones[i].first;	
			tabla += '\t';
			tabla += direcciones[i].second;
		}
	}
	else tabla = "no hay registros";

	result = strdup(tabla.c_str());

	return &result;
}

char **
vtabla_1_svc(char *arg1,  struct svc_req *rqstp)
{
	static char * result;
	string tabla;
	string dns;
	char *host;
	char * *resultHost;
	CLIENT *clnt;
	const string hostip = "localhost";
	
	host = strdup(hostip.c_str());
	tabla.clear();
	dns = string(arg1);

	if (dns == "1") {

		if (direcciones.size() > 0) {

			for (int i = 0; i < direcciones.size(); i++) {

				tabla += '\n';
				tabla += direcciones[i].first;	
				tabla += '\t';
				tabla += direcciones[i].second;
			}
		}
		else tabla = "no hay registros";

		result = strdup(tabla.c_str());
	}
	else if (dns == "2") {

		clnt = clnt_create (host, SERVICIOBASICODEREGISTRO2, DNS2, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}

		resultHost = visualizartabladns_2(clnt);
		if (resultHost == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}

		result = *resultHost;
		
	}
	else result =strdup(string("DNS desconocido").c_str());

	return &result;
}

///////////////////////////////////////////////////////////////////////
