/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVICIOBASICODEREGISTRO_H_RPCGEN
#define _SERVICIOBASICODEREGISTRO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SERVICIOBASICODEREGISTRO 0x20000001
#define DNS 1
#define SERVICIOBASICODEREGISTRO2 0x20000002
#define DNS2 2

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTRA 1
extern  char ** registra_1(char *, CLIENT *);
extern  char ** registra_1_svc(char *, struct svc_req *);
#define BORRA 2
extern  int * borra_1(char *, CLIENT *);
extern  int * borra_1_svc(char *, struct svc_req *);
#define BUSCAIP 3
extern  char ** buscaip_1(char *, CLIENT *);
extern  char ** buscaip_1_svc(char *, struct svc_req *);
#define VISUALIZARTABLADNS 4
extern  char ** visualizartabladns_1(CLIENT *);
extern  char ** visualizartabladns_1_svc(struct svc_req *);
#define VTABLA 5
extern  char ** vtabla_1(char *, CLIENT *);
extern  char ** vtabla_1_svc(char *, struct svc_req *);
extern int serviciobasicoderegistro_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTRA 1
extern  char ** registra_1();
extern  char ** registra_1_svc();
#define BORRA 2
extern  int * borra_1();
extern  int * borra_1_svc();
#define BUSCAIP 3
extern  char ** buscaip_1();
extern  char ** buscaip_1_svc();
#define VISUALIZARTABLADNS 4
extern  char ** visualizartabladns_1();
extern  char ** visualizartabladns_1_svc();
#define VTABLA 5
extern  char ** vtabla_1();
extern  char ** vtabla_1_svc();
extern int serviciobasicoderegistro_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVICIOBASICODEREGISTRO_H_RPCGEN */
