//José María Gómez García A2 DSD

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ServicioBasicoDeRegistro.h"

char *peticion;
char *maquina;

void
serviciobasicoderegistro_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *registra_1_arg1;
	int  *result_2;
	char *borra_1_arg1;
	char * *result_3;
	char *buscaip_1_arg1;
	char * *result_4;
	char * *result_5;
	char *vtabla_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVICIOBASICODEREGISTRO, DNS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if (strncmp(peticion, "registra", 8) == 0) {

		registra_1_arg1 = maquina;

		result_1 = registra_1(registra_1_arg1, clnt);
		if (result_1 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else printf ("Registra: %s\n", *result_1);
	}
	else if (strncmp(peticion, "borra", 5) == 0) {

		borra_1_arg1 = maquina;

		result_2 = borra_1(borra_1_arg1, clnt);
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else printf ("Borra: %i\n", *result_2);
	}
	else if (strncmp(peticion, "buscaip", 7) == 0) {

		buscaip_1_arg1 = maquina;

		result_3 = buscaip_1(buscaip_1_arg1, clnt);
		if (result_3 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else printf ("Buscaip: %s\n", *result_3);

	}
// EXÁMEN /////////////////////////////////////////////////////////////
	else if (strncmp(peticion, "visualizartabladns", 19) == 0) {

		result_4 = visualizartabladns_1(clnt);
		if (result_4 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else printf ("Tabla DNS: %s\n", *result_4);

	}
	else if (strncmp(peticion, "vtabla", 6) == 0) {

		vtabla_1_arg1 = maquina;

		result_5 = vtabla_1(vtabla_1_arg1, clnt);
		if (result_5 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else printf ("Tabla DNS: %s\n", *result_5);

	}
///////////////////////////////////////////////////////////////////////
	else printf("%s: Operación no válida\n", peticion);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	peticion = argv[2];
	maquina = argv[3];
	
	serviciobasicoderegistro_1 (host);
exit (0);
}
