//José María Gómez García A2 DSD

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ServicioBasicoDeRegistro2.h"

char *peticion;
char *maquina;

void
serviciobasicoderegistro2_2(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *registra_2_arg1;
	int  *result_2;
	char *borra_2_arg1;
	char * *result_3;
	char *buscaip_2_arg1;
	char * *result_4;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVICIOBASICODEREGISTRO2, DNS2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if (strncmp(peticion, "registra", 8) == 0) {

		registra_2_arg1 = maquina;

		result_1 = registra_2(registra_2_arg1, clnt);
		if (result_1 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else printf ("Registra: %s\n", *result_1);
	}
	else if (strncmp(peticion, "borra", 5) == 0) {

		borra_2_arg1 = maquina;

		result_2 = borra_2(borra_2_arg1, clnt);
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else printf ("Borra: %i\n", *result_2);
	}
	else if (strncmp(peticion, "buscaip", 7) == 0) {

		buscaip_2_arg1 = maquina;

		result_3 = buscaip_2(buscaip_2_arg1, clnt);
		if (result_3 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else printf ("Buscaip: %s\n", *result_3);

	}
// EXÁMEN /////////////////////////////////////////////////////////////
	else if (strncmp(peticion, "visualizartabladns", 19) == 0) {

		result_4 = visualizartabladns_2(clnt);
		if (result_4 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else printf ("Tabla DNS: %s\n", *result_4);

///////////////////////////////////////////////////////////////////////
	} else printf("%s: Operación no válida\n", peticion);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	peticion = argv[2];
	maquina = argv[3];
	
	serviciobasicoderegistro2_2 (host);
exit (0);
}
