/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ServicioBasicoDeRegistro2.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static char **
_registra_2 (char * *argp, struct svc_req *rqstp)
{
	return (registra_2_svc(*argp, rqstp));
}

static int *
_borra_2 (char * *argp, struct svc_req *rqstp)
{
	return (borra_2_svc(*argp, rqstp));
}

static char **
_buscaip_2 (char * *argp, struct svc_req *rqstp)
{
	return (buscaip_2_svc(*argp, rqstp));
}

static char **
_visualizartabladns_2 (void  *argp, struct svc_req *rqstp)
{
	return (visualizartabladns_2_svc(rqstp));
}

static void
serviciobasicoderegistro2_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *registra_2_arg;
		char *borra_2_arg;
		char *buscaip_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REGISTRA:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _registra_2;
		break;

	case BORRA:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _borra_2;
		break;

	case BUSCAIP:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _buscaip_2;
		break;

	case VISUALIZARTABLADNS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _visualizartabladns_2;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SERVICIOBASICODEREGISTRO2, DNS2);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SERVICIOBASICODEREGISTRO2, DNS2, serviciobasicoderegistro2_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SERVICIOBASICODEREGISTRO2, DNS2, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SERVICIOBASICODEREGISTRO2, DNS2, serviciobasicoderegistro2_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SERVICIOBASICODEREGISTRO2, DNS2, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
